import Foundation
import XCTest

/// Reads the corpus generated by `scripts/gen_vectors.py`.
///
/// The files were produced by an independent Python implementation from the
/// format specifications, so passing against them is evidence about the
/// format -- not evidence that this port agrees with itself.
struct VectorCorpus {
    struct Member: Decodable, Equatable {
        let name: String
        let size: Int
        let sha256: String
    }

    struct Expectations: Decodable {
        var members: [Member]?
        var pages: Int?
        var revision: Int?
        var aesBits: Int?
        var headerEncrypted: Bool?
        var spinCount: Int?
        var innerZip: Bool?

        enum CodingKeys: String, CodingKey {
            case members, pages, revision
            case aesBits = "aes_bits"
            case headerEncrypted = "header_encrypted"
            case spinCount = "spin_count"
            case innerZip = "inner_zip"
        }
    }

    struct Vector: Decodable {
        let id: String
        let file: String
        let format: String
        let protection: String
        let removable: Bool
        let password: String?
        let notes: String
        let expect: Expectations
    }

    let root: URL
    let vectors: [Vector]
    let passwords: [String: String]

    private struct Manifest: Decodable {
        let version: Int
        let passwords: [String: String]
        let vectors: [Vector]
    }

    static func load(file: StaticString = #filePath, line: UInt = #line) throws -> VectorCorpus {
        let root: URL
        if let env = ProcessInfo.processInfo.environment["FPR_VECTORS"] {
            root = URL(fileURLWithPath: env)
        } else {
            // ios/FprKit/Tests/FprKitTests/ -> repo root -> build/vectors
            root = URL(fileURLWithPath: "\(file)")
                .deletingLastPathComponent().deletingLastPathComponent()
                .deletingLastPathComponent().deletingLastPathComponent()
                .deletingLastPathComponent()
                .appendingPathComponent("build/vectors")
        }
        let data = try Data(contentsOf: root.appendingPathComponent("manifest.json"))
        let manifest = try JSONDecoder().decode(Manifest.self, from: data)
        return VectorCorpus(root: root, vectors: manifest.vectors, passwords: manifest.passwords)
    }

    func vector(_ id: String) throws -> Vector {
        guard let vector = vectors.first(where: { $0.id == id }) else {
            throw XCTSkip("vector \(id) not in corpus")
        }
        return vector
    }

    func url(_ id: String) throws -> URL {
        root.appendingPathComponent(try vector(id).file)
    }

    func data(_ id: String) throws -> Data {
        try Data(contentsOf: try url(id))
    }

    /// Expected plaintext members, keyed by name.
    func members(_ id: String) throws -> [String: Member] {
        let members = try vector(id).expect.members ?? []
        return Dictionary(uniqueKeysWithValues: members.map { ($0.name, $0) })
    }

    var correctPassword: String { passwords["correct"]! }
    var wrongPassword: String { passwords["wrong"]! }
}
