plugins {
    alias(libs.plugins.kotlin.jvm)
}

// Deliberately a plain JVM module, not an Android library: the engine has no
// Android dependencies, so its tests run on the JVM in milliseconds instead of
// needing an emulator.
kotlin {
    jvmToolchain(21)
}

dependencies {
    implementation(libs.commons.compress)
    implementation(libs.pdfbox)
    // Commons Compress needs this for LZMA/LZMA2, which 7-Zip uses.
    implementation(libs.xz)
    testImplementation(libs.junit)
    testImplementation(libs.gson)
}

tasks.test {
    useJUnit()
    // The corpus is generated by scripts/gen_vectors.py before the test run.
    systemProperty("fpr.vectors", System.getProperty("fpr.vectors") ?: "${rootDir.parentFile}/build/vectors")
    testLogging { events("failed") }
}
