package dev.jayanth.fpr

import com.google.gson.Gson
import com.google.gson.annotations.SerializedName
import java.io.File

/**
 * Reads the corpus generated by `scripts/gen_vectors.py`.
 *
 * The files come from an independent Python implementation of the same
 * specifications, so passing here is evidence about the format rather than
 * evidence that this port agrees with itself.
 */
class VectorCorpus(val root: File, private val manifest: Manifest) {

    data class Member(val name: String, val size: Int, val sha256: String)

    data class Expectations(
        val members: List<Member>? = null,
        val pages: Int? = null,
        val revision: Int? = null,
        @SerializedName("aes_bits") val aesBits: Int? = null,
        @SerializedName("header_encrypted") val headerEncrypted: Boolean? = null,
        @SerializedName("spin_count") val spinCount: Int? = null,
    )

    data class Vector(
        val id: String,
        val file: String,
        val format: String,
        val protection: String,
        val removable: Boolean,
        val password: String?,
        val notes: String,
        val expect: Expectations,
    )

    data class Manifest(
        val version: Int,
        val passwords: Map<String, String>,
        val vectors: List<Vector>,
    )

    val vectors: List<Vector> get() = manifest.vectors
    val correctPassword: String get() = manifest.passwords.getValue("correct")
    val wrongPassword: String get() = manifest.passwords.getValue("wrong")

    fun vector(id: String): Vector =
        vectors.firstOrNull { it.id == id } ?: error("vector '$id' is not in the corpus")

    fun file(id: String): File = File(root, vector(id).file)

    fun bytes(id: String): ByteArray = file(id).readBytes()

    fun members(id: String): Map<String, Member> =
        (vector(id).expect.members ?: emptyList()).associateBy { it.name }

    companion object {
        fun load(): VectorCorpus {
            val root = File(
                System.getProperty("fpr.vectors")
                    ?: error("fpr.vectors system property is not set")
            )
            val manifest = File(root, "manifest.json")
            require(manifest.isFile) {
                "vector corpus missing at $root -- run scripts/gen_vectors.py first"
            }
            return VectorCorpus(root, Gson().fromJson(manifest.readText(), Manifest::class.java))
        }
    }
}
